### PR TITLE
remove VMMAP permission from stack cap

### PR DESCRIPTION
**Pull request by brettferdosi**
also modify cheritest accordingly

### CODE REVIEW

**Comment by jrtc27** [comment]
But if doing that we'd need to be careful to ensure AT_BASE still has VMMAP so that rtld can mprotect itself. Our CheriBSD is currently too outdated to include D25319 but that will come in the next merge (though we may want to cherry-pick it sooner so we can check we don't break it).

**Comment by jrtc27** [comment]
> I saw that comment - we currently also use CHERI_PERMS_USERSPACE_DATA to create ddc for hybrid binaries, so I didn't modify it. Clearing the VMMAP permission in exec_copyout_strings is a better solution, I'll make the change.

Is there a reason why DDC needs VMMAP? The permission is meaningless for the hybrid ABI.

**Comment by jrtc27** [comment]
(but if we really do want DDC to have VMMAP, that's fine, we can just add the permission to DDC specifically after removing it from CHERI_PERMS_USERSPACE_DATA)

**Comment by brettferdosi** [comment]
> > I saw that comment - we currently also use CHERI_PERMS_USERSPACE_DATA to create ddc for hybrid binaries, so I didn't modify it. Clearing the VMMAP permission in exec_copyout_strings is a better solution, I'll make the change.
> 
> Is there a reason why DDC needs VMMAP? The permission is meaningless for the hybrid ABI.

There's a test for it, but I'm also not sure why it should be there. Perhaps cleaning up CHERI_PERMS_USERSPACE_DATA and related things should be a separate PR?

**Comment by jrtc27** [comment]
> > > I saw that comment - we currently also use CHERI_PERMS_USERSPACE_DATA to create ddc for hybrid binaries, so I didn't modify it. Clearing the VMMAP permission in exec_copyout_strings is a better solution, I'll make the change.
> > 
> > 
> > Is there a reason why DDC needs VMMAP? The permission is meaningless for the hybrid ABI.
> 
> There's a test for it, but I'm also not sure why it should be there. Perhaps cleaning up CHERI_PERMS_USERSPACE_DATA and related things should be a separate PR?

Well no, there's no point making a targeted fix for the stack capability if we then need to go back and fix the problem more generally and revert (/ render pointless given it'll just become a no-op permission masking) the targeted fix.

**Comment by brooksdavis** [comment]
I think we likely want to address the comment above the definition of CHERI_PERMS_USERSPACE_DATA and drop VMMAP there and add it back as needed instead.

**Comment by arichardson** [comment]
See https://github.com/CTSRD-CHERI/cheribsd/pull/864

**Pull request closed without merging**
