### PR TITLE
Merge prerequisite upstream bhyve changes

### PR DESCRIPTION
**Pull request by markjdb**
This is required for bhyve support on Morello. I split out upstream commits into a separate PR since they're self-contained and won't break anything (they modify only usr.sbin/bhyve/*), and the main PR is quite large.

### CODE REVIEW

**Comment by bsdjhb** [comment]
Would it be possible to use cherry-pick -x to merge these?  I make use of the -x annotations when merging upstream changes to figure out upstream commits I can skip during the merge process.  Sorry, I know that means redoing this PR in effect. :(

**Comment by markjdb** [comment]
> Would it be possible to use cherry-pick -x to merge these? I make use of the -x annotations when merging upstream changes to figure out upstream commits I can skip during the merge process. Sorry, I know that means redoing this PR in effect. :(

Certainly, done.

**Review by bsdjhb — APPROVED** [review]
I've tried to restart CI, hopefully it will build fine next time

**Comment by markjdb** [comment]
> I've tried to restart CI, hopefully it will build fine next time

Looks like it's still unhappy...

**Comment by jrtc27** [comment]
I could see no evidence of it having been retried, so I kicked it myself

**Comment by bsdjhb** [comment]
> I could see no evidence of it having been retried, so I kicked it myself

Yeah, the Jenkins UI has changed yet again. :(  I clicked on the green "Rebuild" button in the top right of the new page, but that didn't seem to do anything.

**Comment by jrtc27** [comment]
The UI's the same, the plugin just links to a different page now. You can still get to the old Blue Ocean page.

**Comment by brooksdavis** [comment]
Looks like CI is now happy

**Pull request merged**
