### PR TITLE
Purecap merge dec30

### PR DESCRIPTION
**Pull request by bsdjhb**

### CODE REVIEW

**Comment by bsdjhb** [comment]
Letting this run through CI.  This doesn't have any further cleanups to reservations bits such as vm_map_remove, just enough to get hello world running again locally.

**Comment by jrtc27** [comment]
Should the mismerge commit be folded into the actual merge commit? It didn't used to matter as the stack came from vectp/destp which ultimately did a CSetAddr with sv_psstrings.

**Comment by bsdjhb** [comment]
Merging would require doing a rebase of the merge commit which would seem fraught with peril.

**Comment by bsdjhb** [comment]
Hmm, seems the purecap kernel leaks vm_pointer_t into userland.

**Comment by bsdjhb** [comment]
> Or make it a macro? I can imagine this going wrong if we have headers that want to include cheric.h themselves and do so before frame.h.

We do tend to be consistent about doing <cheri/*> after <machine/*>.  I actually think this probably belongs in <machine/frame.h> as it is much more specific to frame.h and not generic to CHERI C.  I think that was fraught with its own peril though which is why I put it in cheric.h.  The approach I used seemed the most expedient for now as I'm not fully sure what the right solution is.

**Comment by bsdjhb** [comment]
Hmm, remaining test failure (which you can't see from the test output but I've reproduced locally) is this (and only on MIPS):

```
Unexpected failures:
  test_tls_threads: pthread_cond_wait: Operation not permitted
```

**Comment by bsdjhb** [comment]
The failure is not deterministic though, sometimes it fails, sometimes if succeeds, sometimes it hangs. :(

**Pull request merged**
