### PR TITLE
Include SMBFS kernel modules in QEMU kernels

### PR DESCRIPTION
**Pull request by arichardson**
This is currently needed for running tests on RISC-V

### CODE REVIEW

**Comment by jrtc27** [comment]
These belong in the QEMU config. We don't want them in most GENERIC/GENERIC-derived kernels.

**Comment by arichardson** [comment]
We currently use CHERI_SPIKE as the MFS_ROOT kernel that is tested in QEMU, so we need it there too. Are the extra few KB of code a problem in a GENERIC kernel? We can disable it for the FPGA ones.

**Comment by jrtc27** [comment]
GENERIC consistently means the same thing across all architectures and is an upstream thing, so I don't want to diverge there. Using CHERI_SPIKE as the MFS_ROOT QEMU kernel is wrong; we should either rename it or have (CHERI_)QEMU_MFS_ROOT configs (I prefer the latter; having separate SPIKE/QEMU/FETT/GFE kernel configs makes it trivial to pick the right one, and the configs are tiny, they all inherit from GENERIC and tweak things, but combining them into just a few configs means you have to stop and think about which properties you need for your target platform every time, and risk getting it wrong).

**Comment by arichardson** [comment]
Makes sense, I was just trying to be lazy 😢

**Comment by jrtc27** [comment]
Looks better to me.

**Pull request merged**
