### PR TITLE
Run boot smoketest for RISC-V in jenkins

### PR DESCRIPTION
**Pull request by arichardson**

### CODE REVIEW

**Comment by jrtc27** [comment]
risc64-purecap doesn't work because we have no C++, and thus no devd to automatically bring up the interface and run dhclient.

**Comment by arichardson** [comment]
> riscv64-purecap doesn't work because we have no C++, and thus no devd to automatically bring up the interface and run dhclient.

Trivial workaround committed in https://github.com/CTSRD-CHERI/cheribuild/commit/67e3763290c1cf8b7e12b485408326060640bef3

**Comment by arichardson** [comment]
I guess we should wait until the cheritest failures have been addressed before merging this. Will look into that tomorrow.

**Comment by arichardson** [comment]
> It doesn't bound global capabilities in hybrid mode either. It's just that `__cheri_tocap` doesn't try to infer bounds from context in the fragile way that MIPS does.

Yes. I simply wrote "RISC-V does not bound stack capabilities in hybrid mode" in the comment since this is cheritest_bounds_stack and is checking bounds on stack allocations.

Seems like all tests are passing now. Good to merge?

**Comment by jrtc27** [comment]
> > It doesn't bound global capabilities in hybrid mode either. It's just that `__cheri_tocap` doesn't try to infer bounds from context in the fragile way that MIPS does.
> 
> Yes. I simply wrote "RISC-V does not bound stack capabilities in hybrid mode" in the comment since this is cheritest_bounds_stack and is checking bounds on stack allocations.

Right, but by qualifying with "stack" you imply that other capabilities might be bounded by the compiler, which is false and thus actively misleading.
> Seems like all tests are passing now. Good to merge?

Once the comment is fixed, yes.

**Comment by arichardson** [comment]
> > > It doesn't bound global capabilities in hybrid mode either. It's just that `__cheri_tocap` doesn't try to infer bounds from context in the fragile way that MIPS does.
> > 
> > 
> > Yes. I simply wrote "RISC-V does not bound stack capabilities in hybrid mode" in the comment since this is cheritest_bounds_stack and is checking bounds on stack allocations.
> 
> Right, but by qualifying with "stack" you imply that other capabilities might be bounded by the compiler, which is false and thus actively misleading.
That's not what I meant to say and I didn't consider it could be interpreted that way. But I see what you mean now. Should be fixed in the follow-up commit.

**Pull request merged**
