### PR TITLE
Fix warnings in purecap pmcstat

### PR DESCRIPTION
**Pull request by bsdjhb**
- **hwpmc: Use ptraddr_t instead of uintfptr_t**
- **pmc,pmcstat: Re-enable -Werror**

### CODE REVIEW

**Comment by bsdjhb** [comment]
I do not know if this change has implications on the file formats used by pmcstat.  I'm also not sure if we want to carry this large of a local diff.

**Comment by jrtc27** [comment]
I believe the current interchange format is plain addresses (see PMCLOG_{EMIT,READ}ADDR)

**Comment by bsdjhb** [comment]
I briefly tested this on my morello box and `pmcstat -T -S cpu_cycles` still works after these changes.

**Comment by jrtc27** [comment]
The real question is whether that's true when you mix kernel and userspace either side of this change (easiest approach could just be a 24.05 jail).

**Comment by bsdjhb** [comment]
I can boot an old kernel on my box leaving userspace in tact, etc.

**Comment by bsdjhb** [comment]
I have tested the various matrix of combinations of pmcstat binaries across kernels (old and new binaries vs old and new kernels (both hybrid and purecap)) using pmcstat -T -S cpu_cycles and it worked in all cases.

**Pull request merged**
