### PR TITLE
Align with upstream patch for host-symlinks on macOS/arm64

### PR DESCRIPTION
**Pull request by jrtc27**

### CODE REVIEW

**Comment by arichardson** [comment]
If you cherry-pick https://github.com/freebsd/freebsd-src/commit/34ac629b40e68e5394fe0a27e47c73a875d9f8cb this should hopefully also fix the "PATH with spaces" issue from https://github.com/CTSRD-CHERI/cheribuild/issues/341

**Comment by jrtc27** [comment]
We already have downstream diffs in CheriBSD to support that AFAICT

**Comment by bsdjhb** [comment]
Is this ready to land after my next merge finishes?

**Comment by jrtc27** [comment]
Should be

**Pull request merged**
