### PR TITLE
Dubious cheri_bound fixes

### PR DESCRIPTION
**Pull request by brooksdavis**

### CODE REVIEW

**Comment by qwattash** [comment]
We should either leave cheri_bounds for now or pick d0682a235898dee9 which uses `cheri_kern_setbounds` as `cheri_setbounds` will fail for hybrid in those cases.

**Comment by bsdjhb** [comment]
I think for now we can just leave cheri_bounds (if it compiles with the cast removed) and do the cheri_kern_* change separately after riscv is merged since we want to do that today.

**Comment by qwattash** [comment]
I agree, it is best to split the two things since it not a functional change.

**Comment by brooksdavis** [comment]
abandon, this was used to communication purposes

**Pull request closed without merging**
