### PR TITLE
32-bit Fixes

### PR DESCRIPTION
**Pull request by jrtc27**
Found by building MIPS o32 libraries.

### CODE REVIEW

**Review by arichardson — APPROVED** [review]
LGTM although I do wonder whether we still need the inline asm in jdw57_memcpy.c. I think the delay slot in the loop is still not filled when building with debug info, but maybe the other capability-aware memcpy doesn't have that problem?

**Comment by jrtc27** [comment]
I'm unconvinced we need the file at all but it's what we have. My main objection to it is its desire to warn you about memcpy's that clear tags due to misalignment given it happens sometimes due to uninitialised stack memory, I assume generally in large on-stack buffers that are only part-filled.

**Review by bsdjhb — APPROVED** [review]

**Review by brooksdavis — APPROVED** [review]
It looks like libjpeg has no remaining consumers so we likely should remove it.

**Comment by jrtc27** [comment]
I guess that was for the old DE4 demo code then?

**Comment by brooksdavis** [comment]
Yeah, I can't remember if we supported JPEGs in pictview or if it was just the web browser, but one of those.

**Pull request merged**
