### PR TITLE
Dev merge

### PR DESCRIPTION
**Pull request by bsdjhb**

### CODE REVIEW

**Comment by jrtc27** [comment]
Ooh the new (from this branch's perspective) AIO test is timing out on purecap kernels. Also test_initregs_pcc is failing on MIPS for some reason with "code length 0x2000000000 should be 0x8000000000"?

**Comment by bsdjhb** [comment]
The amd64 panic has existed on this branch before, and while it needs to be fixed at some point, it probably shouldn't block this merge.  I've no idea if the MIPS thing is an old failure or a new one as a result of the merge.

**Comment by jrtc27** [comment]
https://ctsrd-build.cl.cam.ac.uk/blue/organizations/jenkins/CheriBSD-pipeline/detail/cheri-purecap-kernel/42/tests seems to suggest it's not new, though that has fewer instances of the failure.

**Comment by qwattash** [comment]
> Ooh the new (from this branch's perspective) AIO test is timing out on purecap kernels. Also test_initregs_pcc is failing on MIPS for some reason with "code length 0x2000000000 should be 0x8000000000"?

I remember attempting to dig at that. IIRC it was an issue with the ifdefs around the macro that defines the user code size, however I was unsure how to best fix it at the time.

**Comment by bsdjhb** [comment]
These extra fixes are what I needed to get MIPS to boot again in qemu with the stock config file.  I need to confirm the cheritest results (that test_initregs_pcc is the only regression) and also need to confirm the MIPS hybrid kernel still works ok.

**Comment by bsdjhb** [comment]
Tracked down the initregs_pcc failure to this:

```
#ifdef __mips_n64
#ifndef CHERI_PURECAP_KERNEL
#define	NPDEPGSHIFT		9               /* LOG2(NPTEPG) */
#else /* CHERI_PURECAP_KERNEL */
#define NPDEPGSHIFT		8		/* LOG2(NPDEPG) */
#endif /* CHERI_PURECAP_KERNEL */
```

This affects the value of NBSEG which in turn affects VM_MAXUSER_ADDRESS.  NPDEPG is also one power of 2 lower, so combined that results in two powers of two, hence the leading '0x8' becomes '0x2'.

**Comment by bsdjhb** [comment]
There isn't an existing sysctl to report the sv_maxuser address that a given process is using, or even just VM_MAXUSER_ADDRESS.  We could also just remove this test as being somewhat pointless for hybrid?

**Review by arichardson — COMMENTED** [review]
I think we can probably merge this since there are no new failures?

**Comment by jrtc27** [comment]
Yeah let's drain this backlog so things can move forwards again.

**Comment by bsdjhb** [comment]
Will do in a bit.

**Pull request merged**
