### PR TITLE
Merge dev 20201030

### PR DESCRIPTION
**Pull request by arichardson**

### CODE REVIEW

**Comment by arichardson** [comment]
We probably want to fast-forward push dev to master instead of merging this, so that the hashes don't change?

**Review by jrtc27 — CHANGES_REQUESTED** [review]
(dummy review to block accidental merging)

**Comment by jrtc27** [comment]
> We probably want to fast-forward push dev to master instead of merging this, so that the hashes don't change?

Yes, absolutely.

**Review by brooksdavis — APPROVED** [review]
Sounds good.  Please ff-merge and push manually since GitHub's merge is stupid.

**Pull request merged**
