### PR TITLE
Various TDA19988 fixes

### PR DESCRIPTION
**Pull request by jrtc27**
- tda19988: Implement a non-stub mode_valid to filter unsupported resolutions
- tda19988: Properly implement mode_set/bridge_enable/bridge_disable flow
- tda19988: Fix divisor calculation
- komeda: Drop temporary resolution hack

### CODE REVIEW

**Review by bsdjhb — COMMENTED** [review]
Confirmed that this does allow my monitor to go to sleep at sddm.

**Review by bsdjhb — COMMENTED** [review]
I assume this supplants #1618 btw since the second commit here is a squash of that?

**Comment by jrtc27** [comment]
> I assume this supplants #1618 btw since the second commit here is a squash of that?

Partially. This doesn't change anything for komeda. And I wrote it from scratch (other than the enable / disable bits), so it's slightly different (e.g. mode vs adjusted_mode).

**Comment by kwitaszczyk** [comment]
I confirm this patch works correctly on my screen - ASUS ProArt Display PA148CTV. Instead of displaying garbage, the screen sleeps due to inactivity in sddm.

**Review by kwitaszczyk — APPROVED** [review]
I confirm this patch works correctly on my screen - ASUS ProArt Display PA148CTV. Instead of displaying garbage, the screen sleeps due to inactivity in sddm.

**Pull request merged**
