### PR TITLE
Backport more of my upstreamed changes

### PR DESCRIPTION
**Pull request by arichardson**
Mostly to get the lorder.sh change and to resolve the merge conflicts in make.py

### CODE REVIEW

**Review by brooksdavis — APPROVED** [review]

**Comment by arichardson** [comment]
Seems like we have duplicate .o files that lorder filtered out. Will fix tomorrow.

**Comment by jrtc27** [comment]
Ah, that's because those are the syscalls we add custom C wrappers for due to being varargs. ISTR commenting when adding fcntl or whatever it was that we weren't removing the assembly file from the sources and being told that it was fine it just overrode the source for the .pico, but presumably we're getting foo.pico from substituting both the .c sources and the .S sources.

**Comment by jrtc27** [comment]
Yeah, I think
https://github.com/CTSRD-CHERI/cheribsd/blob/712258bde6a5867576a6f842b22fd1688a637ba2/lib/libc/sys/Makefile.inc#L98
should just be deleted; `S_NU` is in `SRCS` so is presumably automatically being added to `OBJS` already.

**Comment by jrtc27** [comment]
Yep, reproduced locally and fixed by the following diff as expected:
```diff
diff --git a/lib/libc/sys/Makefile.inc b/lib/libc/sys/Makefile.inc
index 60ff36cfb167..a0ba207ba7f5 100644
--- a/lib/libc/sys/Makefile.inc
+++ b/lib/libc/sys/Makefile.inc
@@ -95,7 +95,6 @@ INTERPOSED:=	${INTERPOSED:N${_nu}}
 S_NU+=		${NO_UNDERSCORE:C/^.*$/_&.S/}
 SRCS+=		${NO_UNDERSCORE:S/$/.c/} ${S_NU}
 NOASM+=		${NO_UNDERSCORE:S/$/.o/}
-OBJS+=		${S_NU:S/.S$/.o/}
 .endif
 
 SRCS+=	${INTERPOSED:S/$/.c/}
```

**Pull request merged**
