### PR TITLE
[MIPS purecap] Default to compiling with address interpretation of uintcap_t

### PR DESCRIPTION
**Pull request by arichardson**
This will allow us to remove some workarounds for offsets and should
already be the default for RISCV.

### CODE REVIEW

**Comment by bsdjhb** [comment]
Is the kernel separate from userland?  Also, it seems like on RISC-V that the compiler still wants explicit __cheri_addr even with this.  It would really reduce diffs to upstream if we could make "plain" integer type casts of capabilities use cgetaddr instead of cfromptr.

**Comment by brooksdavis** [comment]
> Is the kernel separate from userland? Also, it seems like on RISC-V that the compiler still wants explicit __cheri_addr even with this. It would really reduce diffs to upstream if we could make "plain" integer type casts of capabilities use cgetaddr instead of cfromptr.

I wonder if the riscv compiler is defaulting to offset mode?  @jrtc27?

**Comment by jrtc27** [comment]
> > Is the kernel separate from userland? Also, it seems like on RISC-V that the compiler still wants explicit __cheri_addr even with this. It would really reduce diffs to upstream if we could make "plain" integer type casts of capabilities use cgetaddr instead of cfromptr.
> 
> I wonder if the riscv compiler is defaulting to offset mode? @jrtc27?

```
clang/lib/Frontend/CompilerInvocation.cpp-  bool UseCheriVaddrMode =
clang/lib/Frontend/CompilerInvocation.cpp:      Args.hasFlag(OPT_cheri_uintcap_addr, OPT_cheri_uintcap_offset, true);
```

That's in target-independent code, so the default should be address everywhere.

**Comment by arichardson** [comment]
I think the problem is that cap to int casts still use ctoptr in hybrid by default. Once I've changed that we can drop the casts.

**Pull request merged**
