### PR TITLE
Backport #2155 to 24.05

### PR DESCRIPTION
**Pull request by jrtc27**

### CODE REVIEW

**Comment by brooksdavis** [comment]
Conceptually I'm ok with this if we don't want do the fast-forward dance. Ideally main would contain the release hash.

**Comment by jrtc27** [comment]
> Conceptually I'm ok with this if we don't want do the fast-forward dance. Ideally main would contain the release hash.

We could also just fast-forward main and releng/24.05. The only additional changes in dev are the KTLS fixes, and I don't understand why we didn't aim to get them in in the first place.

**Comment by brooksdavis** [comment]
> > Conceptually I'm ok with this if we don't want do the fast-forward dance. Ideally main would contain the release hash.
> 
> We could also just fast-forward main and releng/24.05. The only additional changes in dev are the KTLS fixes, and I don't understand why we didn't aim to get them in in the first place.

OK, I'll start that process

**Comment by brooksdavis** [comment]
Superseded by #2158

**Comment by bsdjhb** [comment]
> > Conceptually I'm ok with this if we don't want do the fast-forward dance. Ideally main would contain the release hash.
> 
> We could also just fast-forward main and releng/24.05. The only additional changes in dev are the KTLS fixes, and I don't understand why we didn't aim to get them in in the first place.

I didn't think the KTLS fixes were critical, and wouldn't have merged them to `dev` if we hadn't opened up `dev`, but they are also small, so a fast forward was ok.

**Pull request closed without merging**
