### PR TITLE
Fix problem introduced in #346

### PR DESCRIPTION
**Pull request by arichardson**
mcontext.mc_pc was being used incorrectly.

### CODE REVIEW

**Comment by jrtc27** [comment]
This was just the single `TRAPF_PC_SET_ADDR` -> `update_pcc_offset` change, right, and the rest just cleanups/asserts? If so, seems correct to me.

**Comment by nwf** [comment]
Merging this atop `master` breaks `init`.  Lemme debug in more detail.

**Comment by arichardson** [comment]
> This was just the single `TRAPF_PC_SET_ADDR` -> `update_pcc_offset` change, right, and the rest just cleanups/asserts? If so, seems correct to me.

sys/mips/mips/pm_machdep.c also uses getoffset instead of getaddr for pc.

@nwf by breaking init do you mean the new asserts trigger or some other kind of breakage?

**Comment by jrtc27** [comment]
Oh, right, yes, that too.

**Comment by nwf** [comment]
False alarm; my tree was in bad shape, it seems.  Let me see if I can figure out why init is horked, but I don't think it's anything to do with this PR.

**Pull request merged**
