### PR TITLE
Fix RISC-V build and support LLD

### PR DESCRIPTION
**Pull request by jrtc27**
I believe everything in here that applies to upstream has been submitted (Differential links are in the relevant commit messages) and that the remaining changes are all CheriBSD-specific.

### CODE REVIEW

**Comment by jrtc27** [comment]
I deliberately haven't pushed the `-mno-relax` changes upstream as not all the RISC-V LLD patches are merged, and it's only strictly necessary when using GCC (Clang defaults to not enabling relaxations and doesn't fully support emitting all the necessary relocations yet) and I doubt anyone will want to use LLD without Clang.

**Comment by bsdjhb** [comment]
So I wonder if it isn't time to actually just kill CHERI_CC and friends instead of the ${X_} changes.  That was just a band-aid because clang was used for CHERI but couldn't build mips.  That is no longer true and we use the same CC for both CHERI and plain MIPS now.  I assume that will be our plan going forward for RISC-V as well.  I don't think we need to bother trying to support separate CHERI_CC at this point and instead should just say if you want to build CheriBSD you can't use GCC 4.2.1 as your CC.  (FreeBSD is getting ready to drop GCC 4.2.1 as a supported toolchain in less than a year.)

Using separate TARGET_ARCH's for CHERI also mean that we can move most of the CHERI-specific CFLAGS bits into bsd.cpu.mk under the relevant MACHINE_ARCH checks.

**Comment by jrtc27** [comment]
> So I wonder if it isn't time to actually just kill CHERI_CC and friends instead of the ${X_} changes. That was just a band-aid because clang was used for CHERI but couldn't build mips. That is no longer true and we use the same CC for both CHERI and plain MIPS now. I assume that will be our plan going forward for RISC-V as well. I don't think we need to bother trying to support separate CHERI_CC at this point and instead should just say if you want to build CheriBSD you can't use GCC 4.2.1 as your CC. (FreeBSD is getting ready to drop GCC 4.2.1 as a supported toolchain in less than a year.)

I'm in favour of killing CHERI_CC; having a different XCC and CHERI_CC is definitely a weird corner-case that I don't foresee us needing again.

**Comment by jrtc27** [comment]
> The ptr -> ptr_int rename seems gratuitous perhaps? The real diff seems to be removing the __PTR_TO_INT() macro invocation when the builtin doesn't exist?

Yeah, it's not necessary, just the current `ptr` name felt wrong given there's a `__PTR_TO_INT` call made *before* invoking the macro, so for purecap the argument will be a real `intptr_t`, but for non-purecap it will be a `ptrdiff_t` (or `long` if no such type exists), ie the argument is always already a `PTR_INT_TYPE` (hence the `ptr_int` name).

**Comment by brooksdavis** [comment]
Is there anything left in this change set that we might want?

**Comment by jrtc27** [comment]
I don’t think so but possible the odd hunk is necessary. Doesn’t really make sense to keep the pull request open though, it’s not something we’re ever going to merge, so I’ll close it and we can still refer back to it if necessary.

**Pull request closed without merging**
