### PR TITLE
Cherry pick upstream testsuite fixes

### PR DESCRIPTION
**Pull request by arichardson**
Should get the test suite closer to passing

### CODE REVIEW

**Comment by arichardson** [comment]
I think this can wait until after merging some of these changes from upstream.

**Comment by bsdjhb** [comment]
I've rebased this after merging up through July 30th (which is just after the last update to this PR).  Now it is only a mismerge fix and the non-upstream commit to add a ZFS_TESTS option.

**Comment by bsdjhb** [comment]
Hmm, so how do I force this to run the kyua test suite?

**Comment by jrtc27** [comment]
Go kick https://ctsrd-build.cl.cam.ac.uk/job/CheriBSD-testsuite/job/cherry-pick-testsuite-fixes/

**Comment by bsdjhb** [comment]
@arichardson do we still want the ZFS_TESTS knob?

**Comment by arichardson** [comment]
> @arichardson do we still want the ZFS_TESTS knob?

Might still make sense, since the ZFS tests are broken and report failure instead of unsupported when ksh is not installed...

**Comment by arichardson** [comment]
Obsolete

**Pull request closed without merging**
