### PR TITLE
Fix _openat with a mode argument.

### PR DESCRIPTION
**Pull request by brooksdavis**
Fixes https://github.com/CTSRD-CHERI/FETT/issues/13

Also a couple UX improvements.

### CODE REVIEW

**Comment by brooksdavis** [comment]
UX issues pertain to https://github.com/CTSRD-CHERI/FETT/issues/12

**Comment by jrtc27** [comment]
I _think_ we want to be aliasing the double-underscore ones to single-underscore not the syscall too?

**Comment by brooksdavis** [comment]
I'm just confused about the double-underscore ones.  They don't seem to have any users and aren't in the Symbol.map. The one potential use I've spotted is __open in less, but I'm not even sure that's real.

**Comment by jrtc27** [comment]
Yeah. There's `sys/contrib/octeon-sdk/cvmx-malloc/malloc.c:#define open             __open`, and newlib seems to use it in a few places. I assume everyone's expecting it to be varargs, as that's what it normally is.

**Comment by jrtc27** [comment]
I think this looks good now (though the use of `#ifndef __CHERI_PURE_CAPABILITY__` does my head in more than it perhaps should). Have you tested it fixes vi?

**Comment by brooksdavis** [comment]
Yup, the first batch fixed vi with no arguments for a non-root user.

**Comment by brooksdavis** [comment]
I'm of two minds about the `#ifndef` thing. On one hand non-CHERI is the common case, on the other it is a bit hard to read.

**Comment by jrtc27** [comment]
Yeah... you just have to remember to sound it as "if legacy" in your head then it's not so bad.

**Comment by brooksdavis** [comment]
```
#ifdef __INTEGER_POINTERS__
```

**Pull request merged**
