### PR TITLE
.github: Update the style checker action for CheriBSD

### PR DESCRIPTION
**Pull request by bsdjhb**
This is very expensive to run against merges from dev to main.  Even
for PRs against dev we would only want it to be advisory (and wouldn't
want it for upstream FreeBSD merge PRs).

### CODE REVIEW

**Comment by bsdjhb** [comment]
Actual testing of this is over in a child PR against this branch here: https://github.com/bsdjhb/cheribsd/pull/1

**Comment by bsdjhb** [comment]
This cherry picks several fixes back from FreeBSD to add `--github` support to get per-line annotations and then updates the yaml file for CheriBSD to run against `dev` instead of `main`, and to also always be green by forcing a return value of true.

You can see a sample of the per-file annotations it adds over at https://github.com/bsdjhb/cheribsd/pull/1/files

Note that it runs the checks on each commit, so if you "fix" a style bug in a later commit, you still end up with an annotation at the original location for the bug in the first commit.

**Comment by bsdjhb** [comment]
I looked btw and the clang-format action we use in the disabled clang-format check doesn't support GitHub annotations (I would have tried to fix it to do so otherwise).  I think we should probably just remove the clang-format check if we adopt the changes in the PR.

**Comment by bsdjhb** [comment]
Now updated to only run the style check against the final diff so if a bug gets "fixed" in the middle it doesn't get annotated.

**Review by jrtc27 — APPROVED** [review]

**Pull request merged**
