### PR TITLE
riscv: Don't panic when underflowing imgp->strings during exec

### PR DESCRIPTION
**Pull request by bsdjhb**
The stringspace used to hold argument and environment strings during
exec holds more than just strings.  It also holds the ELF auxiliary,
argument, and environment vectors as well as other ancillary data
pointed to by the ELF auxiliary vector like the stack canary and page
sizes array.  If userland passes the max amount of argument strings
data (ARG_MAX), exec_copyout_strings would underflow imgp->strings
when setting bounds on ustringp.  On current CHERI RISC-V this causes
a kernel panic due to the faulting CSetBounds.  On Morello an eventual
copyout fails due to overflowing bounds.

This commit adds explicit checks against the base of imgp->strings to
detect underflow and fail with E2BIG.  To avoid having to add another
check for imgp->auxv, allocate imgp->auxv before the string space and
initialize imgp->auxv earlier (which I find a bit less confusing in
general).

### CODE REVIEW

**Comment by bsdjhb** [comment]
Note that this does mean that one of the pkill/pgrep-f_test:main tests now fails instead of panics.  I think to make the test not fail we would actually need to make imgp->strings larger to support up to ARG_MAX data.  I worry that due to representability we'd have to allocate 2 * ARG_MAX and not just ARG_MAX + PAGE_SIZE.

**Comment by jrtc27** [comment]
You don't need `2 * ARG_MAX`, just `cheri_round_representable_length(ARG_MAX + PAGE_SIZE)`?

**Comment by jrtc27** [comment]
(Or + whatever the amount of space is that's needed)

**Comment by bsdjhb** [comment]
Yes, I've tested it and it turns out it doesn't round up to just add a page.

**Comment by bsdjhb** [comment]
The test failures are all due to moving auxv.

**Comment by bsdjhb** [comment]
The other approach is in #1813 and is probably a better fix.

**Pull request closed without merging**
