### PR TITLE
Fix munmap/mprotect/minherit allowing untagged capabilities

### PR DESCRIPTION
**Pull request by jrtc27**

### CODE REVIEW

**Comment by arichardson** [comment]
We should probably add test cases for untagged munmap/mprotect to  bin/cheritest/cheritest_cheriabi.c?

**Comment by jrtc27** [comment]
> We should probably add test cases for untagged munmap/mprotect to bin/cheritest/cheritest_cheriabi.c?

Yes we should; are you volunteering? :)

**Comment by jrtc27** [comment]
Confirmed to fix the bug (in case there was any doubt):
```
mmap(0x0,8192,PROT_READ|PROT_WRITE,MAP_SHARED|MAP_ANON,-1,0x0) = 1074847744 (0x4010e000)
mmap(0x0,8192,PROT_READ|PROT_WRITE,MAP_SHARED|MAP_ANON,-1,0x0) = 1083809792 (0x4099a000)
mmap(0x0,8192,PROT_READ|PROT_WRITE,MAP_SHARED|MAP_ANON,-1,0x0) = 1083817984 (0x4099c000)
mmap(0x0,8192,PROT_READ|PROT_WRITE,MAP_SHARED|MAP_ANON,-1,0x0) = 1083826176 (0x4099e000)
mmap(0x0,8192,PROT_READ|PROT_WRITE,MAP_SHARED|MAP_ANON,-1,0x0) = 1083834368 (0x409a0000)
mmap(0x0,8192,PROT_READ|PROT_WRITE,MAP_SHARED|MAP_ANON,-1,0x0) = 1083842560 (0x409a2000)
mmap(0x0,8192,PROT_READ|PROT_WRITE,MAP_SHARED|MAP_ANON,-1,0x0) = 1083850752 (0x409a4000)
mmap(0x0,8192,PROT_READ|PROT_WRITE,MAP_SHARED|MAP_ANON,-1,0x0) = 1083858944 (0x409a6000)
munmap(0x40116000,8192)                          ERR#98 'Memory protection violation'
mmap(0x0,8192,PROT_READ|PROT_WRITE,MAP_SHARED|MAP_ANON,-1,0x0) = 1083867136 (0x409a8000)
mmap(0x0,8192,PROT_READ|PROT_WRITE,MAP_SHARED|MAP_ANON,-1,0x0) = 1083875328 (0x409aa000)
mmap(0x0,8192,PROT_READ|PROT_WRITE,MAP_SHARED|MAP_ANON,-1,0x0) = 1083883520 (0x409ac000)
mmap(0x0,8192,PROT_READ|PROT_WRITE,MAP_SHARED|MAP_ANON,-1,0x0) = 1083891712 (0x409ae000)
mmap(0x0,8192,PROT_READ|PROT_WRITE,MAP_SHARED|MAP_ANON,-1,0x0) = 1083899904 (0x409b0000)
mmap(0x0,8192,PROT_READ|PROT_WRITE,MAP_SHARED|MAP_ANON,-1,0x0) = 1083908096 (0x409b2000)
mmap(0x0,8192,PROT_READ|PROT_WRITE,MAP_SHARED|MAP_ANON,-1,0x0) = 1083916288 (0x409b4000)
mmap(0x0,8192,PROT_READ|PROT_WRITE,MAP_SHARED|MAP_ANON,-1,0x0) = 1083924480 (0x409b6000)
```

**Review by brooksdavis — APPROVED** [review]

**Review by arichardson — COMMENTED** [review]
I can add a test for this. Since if we don't add the test now we will forget and never add it.

**Comment by arichardson** [comment]
I think we should follow what we do for LLVM and add regression tests for any important bug fixes.

**Pull request merged**
