### PR TITLE
Merge ZFS 14.0 EN fixes

### PR DESCRIPTION
**Pull request by bsdjhb**
- zfs: cherry-pick commit from master
- zfs: cherry-pick commit from master
- zfs: cherry-pick commit from master

### CODE REVIEW

**Review by gvnn3 — APPROVED** [review]
LGTM.  Thanks.

**Review by brooksdavis — APPROVED** [review]
Should these have cherry-picked with -x?

**Comment by bsdjhb** [comment]
> Should these have been cherry-picked with -x?

These can't really be cherry-picked normally.  In main they were part of larger ZFS merges.  I cherry-picked the stable/14 commits without changing the log message.  Those had an -x annotation for the commit in the ZFS vendor branch that was the fix, but it's a commit on the ZFS vendor branch, not a commit on main.

**Comment by brooksdavis** [comment]
> > Should these have been cherry-picked with -x?
> 
> These can't really be cherry-picked normally. In main they were part of larger ZFS merges. I cherry-picked the stable/14 commits without changing the log message. Those had an -x annotation for the commit in the ZFS vendor branch that was the fix, but it's a commit on the ZFS vendor branch, not a commit on main.

That's fine. For the previous batch of SA's I recorded the stable/14 commit I'd cherry picked.

**Pull request merged**
