### PR TITLE
Use vendored CHERI-LLVM compiler-rt

### PR DESCRIPTION
**Pull request by jrtc27**

### CODE REVIEW

**Review by arichardson — APPROVED** [review]
I feel like the libgcc_eh code might date back to when there were some changes in CHERI libunwind that broke the non-CHERI build. Good to see it be deleted.

**Review by arichardson — CHANGES_REQUESTED** [review]
Looks like we are still missing some FreeBSD-local changes that are breaking the build?

**Comment by jrtc27** [comment]
Yeah, looks like there are both FreeBSD issues and CheriBSD issues... :( bad FreeBSD upstream not upstreaming to LLVM.

**Comment by jrtc27** [comment]
This should be ready to land now

**Pull request merged**
