### PR TITLE
Jenkins: Run purecap kernel tests in parallel

### PR DESCRIPTION
**Pull request by arichardson**

### CODE REVIEW

**Comment by arichardson** [comment]
Jenkins visualization gets somewhat confused while running the pipeline, but the final result looks more or less reasonable.

**Comment by jrtc27** [comment]
Hm, it's going to look a bit silly once there's Morello in there too (or MIPS)...

**Comment by arichardson** [comment]
> Hm, it's going to look a bit silly once there's Morello in there too (or MIPS)...

I agree, but it does speed up the CI runs by the time it takes to run the hybrid tests (5-15 minutes depending on Jenkins load).
FYI here is the Jenkins bug report: https://issues.jenkins.io/browse/JENKINS-54010

**Comment by qwattash** [comment]
I think as long as it speeds up testing we can cope with UI broken-ness, as unfortunate as it is.

**Comment by arichardson** [comment]
Adding a `stage()` around the parallel doesn't seem to help, so should we merge this as is?

**Comment by jrtc27** [comment]
Yeah, as sad as it is.

**Review by jrtc27 — APPROVED** [review]

**Pull request merged**
