### PR TITLE
Add a -x flag to cheritest to emit JUnit XML

### PR DESCRIPTION
**Pull request by arichardson**
This should allow us to display the results in Jenkins. xmllint and
junitparse appear to be happy with the resulting out.

### CODE REVIEW

**Comment by jrtc27** [comment]
Hmm, `-j` collides with `make -j` etc., so one might reasonably expect this to instead parallelise the tests. What about either `-x` (given it only sets the output format to XML, and you've made XML in general be JUnit) or `-J`?

**Comment by arichardson** [comment]
'x' sounds good, I just looked at the getopt string and picked the first letter that could make sense.

**Comment by arichardson** [comment]
Jenkins test this please.

**Comment by arichardson** [comment]
Okay let's try again: Jenkins test this please.

**Comment by arichardson** [comment]
Maybe this webhook setting works now... Jenkins test this please.

**Pull request merged**
