### PR TITLE
Merge FreeBSD 2021-09-24

### PR DESCRIPTION
**Pull request by bsdjhb**
PR for CI

One possibly non-trivial change is that a local diff we had for throttling entropy gathering from virtio-rng is gone as the wakeup side was removed, and upstream claims to have made changes to throttle entropy collection to work better in virtualization environments.

### CODE REVIEW

**Comment by bsdjhb** [comment]
So with just upstream changes I see `[rand_harvestq]` still chewing a constant 0.1% or so of CPU time.   One of the difficulties is that upstream removed the hook we used to wakeup the thread when /dev/random was read from and so the simplest form would be to just seed on boot and never again.  That's probably ok for QEMU so long as we don't do it on actual Morello boards.

**Comment by jrtc27** [comment]
Is 0.1% a problem? I imagine it was much higher before. There's also the option of making RANDOM_KTHREAD_HZ a tunable.

**Comment by bsdjhb** [comment]
Hmmm, I guess I should see what it was before.  I assumed 0.1% was as it is in the constant top 5 processes in top in an idle system.

**Comment by jrtc27** [comment]
Given intr is ~1.5%, and pagedaemon/bufdaemon are ~0.1% each, I don't think another 0.1% of random harvesting is a problem. I imagine the real problem was read_rate being bumped up to more than 1 so it'd take much more a of a slice.

Though maybe there's a big issue here on FPGA where we don't have a fast entropy source... if we really wanted to we could add a hook back in the two places read_rate_increment was called that kicks harvesting, maybe you could even upstream it guarded by a tunable to benefit low-power devices or something.

**Comment by bsdjhb** [comment]
So on a current dev kernel with Alex's hack removed it used the same CPU amount for me in QEMU morello (0.1%).  Alex's comment was about overheads in QEMU specifically though back in 2018 when it was added.  I'm fine with just dropping the local diff for now, but we might need to reevaluate the specific use case and revisit this in the future.

**Comment by jrtc27** [comment]
QEMU Morello won't use the old code, it was guarded by CPU_CHERI

**Comment by jrtc27** [comment]
Oh, no, GENERIC-MORELLO does set CPU_CHERI

**Comment by bsdjhb** [comment]
CPU_CHERI is used in sys/conf/files for sys/cheri/*.  So one option I was going to use is to make it more dynamic where we checked for a VM (vm_guest != VM_GUEST_NO) and only do the hack when running under QEMU.

**Comment by bsdjhb** [comment]
Sigh, `vm_guest` hasn't been implemented on non-x86 so there isn't an easy way currently to detect QEMU vs real hardware.

**Comment by jrtc27** [comment]
Yeah, and that won't help FPGAs anyway

**Comment by bsdjhb** [comment]
I think for now I will just drop the local diff and we can reimplement it in the future if needed.  I can also try to ask upstream about why they still want to poll for entropy so often.

**Pull request merged**
