### PR TITLE
Jenkins: Also run the boot test for x86 and aarch64

### PR DESCRIPTION
**Pull request by arichardson**

### CODE REVIEW

**Comment by zxombie** [comment]
The arm64 run should be fixed by https://svnweb.freebsd.org/changeset/base/363451

**Comment by arichardson** [comment]
Should I switch cheribuild back to building GENERIC-UP?

**Comment by jrtc27** [comment]
This feels like something we should just cherry-pick. @brooksdavis ?

**Comment by zxombie** [comment]
If you've switched to GENERIC I'd keep it. It's the config that gets the most testing upstream, e.g. the above is unneeded there.

**Pull request merged**
