### PR TITLE
libsys: Add CHERI_LIB_C18N to CFLAGS when appropriate

### PR DESCRIPTION
**Pull request by dpgao**

### CODE REVIEW

**Comment by bsdjhb** [comment]
Hmm, looks like the multi-threaded cheribsdtest binaries using c18n failed tests (or maybe crashed without running any tests?)

**Comment by jrtc27** [comment]
Both ABIs crashed with SIGTRAP

**Comment by dpgao** [comment]
Looks like the `elf_aux_info` stub in libsys is being called.
```
(gdb) r
The program being debugged has been started already.
Start it from the beginning? (y or n) y
Starting program: /bin/cheribsdtest-mt-c18n

Program received signal SIGTRAP, Trace/breakpoint trap.
Breakpoint.
elf_aux_info () at /Volumes/Personal/cheri/cheribsd/lib/libsys/libc_stubs.c:11
(gdb) bt
#0  elf_aux_info () at /Volumes/Personal/cheri/cheribsd/lib/libsys/libc_stubs.c:11
#1  0x000000004038bfc0 in _thr_signal_block_check_fast () at /Volumes/Personal/cheri/cheribsd/lib/libthr/thread/thr_sig.c:167
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

**Comment by jrtc27** [comment]
Why is elf_aux_info a stub? How is that ever meant to work? There's useful information in there...

**Comment by jrtc27** [comment]
Oh I see, it's meant to be filtered such that you get the non-trapping version at run time. So why isn't libsys's definition being used here? It works for non-c18n.

**Comment by dpgao** [comment]
ktrace shows
```
 39137 cheribsdtest-mt-c18 USER  RTLD: error: /usr/lib/c18n/libsys.so.7: Undefined symbol "sigaction_c18n"
 39137 cheribsdtest-mt-c18 USER  RTLD: error: /usr/lib/c18n/libsys.so.7: Could not find symbol sigaction_c18n
```
which causes the filtee to not be loaded. `sigaction_c18n` should probably be moved to `libsys`?

**Comment by dpgao** [comment]
I removed `sigaction_c18n` altogether and makes libsys's interpose table directly refer to RTLD's hook (`_rtld_sigaction`).

**Review by bsdjhb — COMMENTED** [review]
Maybe just drop the first commit and only have the second commit that "fixes" c18n libsys?

**Pull request merged**
