### PR TITLE
Fix EFI support for CHERI-RISC-V

### PR DESCRIPTION
**Pull request by jrtc27**
The U-Boot built by u-boot-baremetal-riscv64(-hybrid) is able to boot a cheribsd-riscv64-purecap image using EFI with these changes.

### CODE REVIEW

**Comment by jrtc27** [comment]
NB: This also means a workaround in morello-dev (disabling pointer provenance errors in libefivar) is no longer needed, so I'm adding the Morello label.

**Comment by arichardson** [comment]
Hmm why is jenkins ignoring XOBJCOPY...

**Comment by jrtc27** [comment]
CTSRD-CHERI/cheribuild@f84796603f39e994e8d89f0c981129ba20ab69fc broke it because:
```
stand/efi/Makefile.inc:29:# XXX: doesn't work with llvm-objcopy!
stand/efi/Makefile.inc:30:OBJCOPY=${WORLDTMP}/usr/bin/objcopy
```

I don't know if that's because it doesn't support `-O efi-app-*` (they only exist for i386/amd64) or because it'll need --allow-broken-links (which is particularly silly for `-O binary`...).

**Review by gnn-juul — APPROVED** [review]

**Comment by arichardson** [comment]
> [CTSRD-CHERI/cheribuild@f847966](https://github.com/CTSRD-CHERI/cheribuild/commit/f84796603f39e994e8d89f0c981129ba20ab69fc) broke it because:
> 
> ```
> stand/efi/Makefile.inc:29:# XXX: doesn't work with llvm-objcopy!
> stand/efi/Makefile.inc:30:OBJCOPY=${WORLDTMP}/usr/bin/objcopy
> ```
> 
> I don't know if that's because it doesn't support `-O efi-app-*` (they only exist for i386/amd64) or because it'll need --allow-broken-links (which is particularly silly for `-O binary`...). Well, the former is definitely true at least, though doesn't affect non-x86 as they have to construct their PE/COFF headers manually.

Ah yeah I forgot about that. Would definitely be nice if this could be made to work with llvm-objcopy.

**Comment by jrtc27** [comment]
> > [CTSRD-CHERI/cheribuild@f847966](https://github.com/CTSRD-CHERI/cheribuild/commit/f84796603f39e994e8d89f0c981129ba20ab69fc) broke it because:
> > ```
> > stand/efi/Makefile.inc:29:# XXX: doesn't work with llvm-objcopy!
> > stand/efi/Makefile.inc:30:OBJCOPY=${WORLDTMP}/usr/bin/objcopy
> > ```
> > 
> > 
> > I don't know if that's because it doesn't support `-O efi-app-*` (they only exist for i386/amd64) or because it'll need --allow-broken-links (which is particularly silly for `-O binary`...). Well, the former is definitely true at least, though doesn't affect non-x86 as they have to construct their PE/COFF headers manually.
> 
> Ah yeah I forgot about that. Would definitely be nice if this could be made to work with llvm-objcopy.

How hard can it be, PE/COFF support already exists... :)

**Review by brooksdavis — APPROVED** [review]

**Pull request merged**
