### PR TITLE
Ldd merge

### PR DESCRIPTION
**Pull request by bsdjhb**
This merges in my upstream commit to ldd.  It also merges an earlier commit that would generate conflicts in the commit to merge otherwise (removing a.out).  Finally, the third commit uses direct rtld on all platforms.  After we catch up with FreeBSD again we could perhaps merge the -t flag to rtld upstream along with the direct exec ldd changes upstream, potentially retiring ldd32 in the process.

Note that ldd does not work on purecap RISC-V shared libraries still as they do not have the FreeBSD ABI tag due to lack of crti.o for purecap ABIs.  @jrtc27 is already aware of an issue with how the comdat notes work now, and fixing that may fix the purecap shared libraries, or alternatively I wonder if we could have a crti.o for purecap that is just crtbrand.o.

### CODE REVIEW

**Comment by arichardson** [comment]
> This merges in my upstream commit to ldd. It also merges an earlier commit that would generate conflicts in the commit to merge otherwise (removing a.out). Finally, the third commit uses direct rtld on all platforms. After we catch up with FreeBSD again we could perhaps merge the -t flag to rtld upstream along with the direct exec ldd changes upstream, potentially retiring ldd32 in the process.
> 
> Note that ldd does not work on purecap RISC-V shared libraries still as they do not have the FreeBSD ABI tag due to lack of crti.o for purecap ABIs. @jrtc27 is already aware of an issue with how the comdat notes work now, and fixing that may fix the purecap shared libraries, or alternatively I wonder if we could have a crti.o for purecap that is just crtbrand.o.

Could we include it in crtbegin.o instead? We can of course change clang to link crti.o again. Not sure what the better solution is.

**Comment by arichardson** [comment]
> > This merges in my upstream commit to ldd. It also merges an earlier commit that would generate conflicts in the commit to merge otherwise (removing a.out). Finally, the third commit uses direct rtld on all platforms. After we catch up with FreeBSD again we could perhaps merge the -t flag to rtld upstream along with the direct exec ldd changes upstream, potentially retiring ldd32 in the process.
> > Note that ldd does not work on purecap RISC-V shared libraries still as they do not have the FreeBSD ABI tag due to lack of crti.o for purecap ABIs. @jrtc27 is already aware of an issue with how the comdat notes work now, and fixing that may fix the purecap shared libraries, or alternatively I wonder if we could have a crti.o for purecap that is just crtbrand.o.
> 
> Could we include it in crtbegin.o instead? We can of course change clang to link crti.o again. Not sure what the better solution is.

I guess the second one would reduce a diff to upstream LLVM, so maybe that?

**Comment by bsdjhb** [comment]
Regardless of how we resolve the brand for RISC-V shared libraries, I think this PR is probably ok to merge?

**Review by arichardson — APPROVED** [review]
Sounds good to me.

**Pull request merged**
