### PR TITLE
Fix a null pointer dereference in kqueue revocation code

### PR DESCRIPTION
**Pull request by markjdb**
This fixes issue #1876 .

### CODE REVIEW

**Review by nwf — COMMENTED** [review]
- We're clear to `knote_free` under `KQ_LOCK()`?
- I wonder how this never came up before.
- Is the `<=` in `<= kq->kq_knhashmask` still right, it's just that `0` is special?

**Comment by markjdb** [comment]
> * We're clear to `knote_free` under `KQ_LOCK()`?

Yes. knote_free() does nothing except free the knote to the slab allocator, which is perfectly fine to do with the mutex held. There is code elsewhere in kern_event.c which does the same thing.

>     * Is the `<=` in `<= kq->kq_knhashmask` still right, it's just that `0` is special?

Yes, `kq_knhashmask` is the largest bucket index in the table. The index for an item is selected with `id & kq_knhashmask`, but a hash mask of 0 means that there is no table.

**Comment by markjdb** [comment]
I force-pushed a build fix but this doesn't seem to have re-run the jenkins jobs, which is presumably why they show up as failed.

**Review by brooksdavis — APPROVED** [review]

**Comment by jrtc27** [comment]
Do we need to care about kn_in_flux in this code?

**Comment by markjdb** [comment]
> [*]Though, ISTR that fork() will not proceed in parallel with a revocation pass. I can't find any code now which would ensure that though, maybe I'm thinking of something from the store-side revoker?

Brooks notes that the revoker will single-thread the process while hoard scanning is done, so I think we're ok. Maybe I should add a comment explaining why I think it's ok to ignore the in-flux state, though.

**Comment by jrtc27** [comment]
> > [*]Though, ISTR that fork() will not proceed in parallel with a revocation pass. I can't find any code now which would ensure that though, maybe I'm thinking of something from the store-side revoker?
> 
> Brooks notes that the revoker will single-thread the process while hoard scanning is done, so I think we're ok. Maybe I should add a comment explaining why I think it's ok to ignore the in-flux state, though.

That would be helpful, thanks

**Pull request merged**
