### PR TITLE
Add a clang-format GitHub action

### PR DESCRIPTION
**Pull request by arichardson**
This checks all the commits in the current PR using
my fork of WolleTD/clang-format-checker.
Ideally, it would also add inline comments but that
might be quite a lot of work.

### CODE REVIEW

**Comment by arichardson** [comment]
Seems to be working okay: https://github.com/CTSRD-CHERI/cheribsd/runs/3626810569?check_suite_focus=true

Obviously we can ignore the clang-format suggestions but for most new code it should be pretty accurate.

**Comment by arichardson** [comment]
This seems to be working now. Is this something we want as an advisory check that can be ignored for cases where clang format is not quite right?

**Review by brooksdavis — APPROVED** [review]
Seems reasonable. We can ignore results when it's touching code we don't care about or can't change.

Is there a way to exclude particular paths if some things become annoying?

**Comment by arichardson** [comment]
> Seems reasonable. We can ignore results when it's touching code we don't care about or can't change.
> 
> Is there a way to exclude particular paths if some things become annoying?



> Seems reasonable. We can ignore results when it's touching code we don't care about or can't change.
> 
> Is there a way to exclude particular paths if some things become annoying?

It's possible to ignore directories by adding a new config file: https://stackoverflow.com/a/57272592

Not sure if there is anything finer-grained.

**Pull request merged**
