### PR TITLE
Merge FreeBSD security advisories (August 7, 2024)

### PR DESCRIPTION
**Pull request by brooksdavis**

### CODE REVIEW

**Comment by brooksdavis** [comment]
I skilled the PF fix. It looks like it applies to code we haven't merged yet and I believe we don't have the upstream CHERI fixes so it doesn't work.

**Comment by jrtc27** [comment]
What about the openssh one?

**Comment by jrtc27** [comment]
(https://www.freebsd.org/security/advisories/FreeBSD-SA-24:08.openssh.asc)

**Review by markjdb — APPROVED** [review]

**Comment by markjdb** [comment]
> What about the openssh one?

This was #2182 .

**Pull request merged**
